<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To date_qcreated_at_lteq</name>
   <tag></tag>
   <elementGuidId>14cb16dd-9fd3-4d59-a10c-18f23e415e6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#q_created_at_lteq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='q_created_at_lteq']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1365c8e9-5870-49f4-8e93-10fc36d68f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4d419885-2e43-4d48-91ce-c7f60aae9c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>change->report#submitForm</value>
      <webElementGuid>f094bc73-f5e5-4569-b77b-958544dd21f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>9c35a27e-464a-45d2-b0de-188722c3cbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q[created_at_lteq]</value>
      <webElementGuid>5136ee0f-5fbc-499b-b9db-ecb9e0010aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>q_created_at_lteq</value>
      <webElementGuid>56cf959b-d8f8-40ed-8095-9a0ef6dd57a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q_created_at_lteq&quot;)</value>
      <webElementGuid>5f674878-af73-43bb-ae5a-60db2a284b2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='q_created_at_lteq']</value>
      <webElementGuid>ac240e39-5467-4ea3-b27d-ce63ed8e874b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchReport']/div/div[3]/input</value>
      <webElementGuid>ebd9f625-e950-449a-9858-ef4d7011bfa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>fbad0b1e-19da-44ec-825f-5b5e732750b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'q[created_at_lteq]' and @id = 'q_created_at_lteq']</value>
      <webElementGuid>65f0849a-e5b6-4c6b-abe7-826b5b950dea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
