<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From date_qcreated_at_gteq</name>
   <tag></tag>
   <elementGuidId>b9b7a213-5884-48bb-9033-173241b7f0e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#q_created_at_gteq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='q_created_at_gteq']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30e0f032-8cd4-4a2a-b830-7fd717264455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>47884d06-095a-46fb-893a-9d41c10c82a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>change->report#submitForm</value>
      <webElementGuid>fada6648-adf8-4840-9b17-5625fb87ecc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>9dac9b38-add6-4662-8077-ef164fc8689f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q[created_at_gteq]</value>
      <webElementGuid>e442cbe8-cd4a-47ce-8545-9d0c5d995e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>q_created_at_gteq</value>
      <webElementGuid>9da536e8-5193-4a16-9bd5-39fd154a4b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q_created_at_gteq&quot;)</value>
      <webElementGuid>04f7a652-a688-4eb8-aa6c-400cd37312d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='q_created_at_gteq']</value>
      <webElementGuid>52c1289b-07f0-48c3-8993-b3025165a35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchReport']/div/div/input</value>
      <webElementGuid>0bc03eae-2840-4ffe-a855-0e56e5cfce20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>09f372db-25ec-42b3-bd04-542c863ede8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'q[created_at_gteq]' and @id = 'q_created_at_gteq']</value>
      <webElementGuid>f0e25f57-99d5-48f3-ba66-2b1d9fc1feef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
