<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_QA-73</name>
   <tag></tag>
   <elementGuidId>1ef2aae6-c947-48be-b088-4414f4919399</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-polSelect-result-520t-73</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-polSelect-result-520t-73']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7ea533c6-8722-423b-9afd-4d13722e86e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--selectable select2-results__option--selected select2-results__option--highlighted</value>
      <webElementGuid>0457dda1-2fd5-4ff0-8159-868f516e821f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-polSelect-result-520t-73</value>
      <webElementGuid>76d041e0-420b-465c-ba67-0cd0372f535f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ef430aaf-56fa-43a1-92aa-54f9a7520e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-data-select2-polSelect-result-520t-73</value>
      <webElementGuid>ef59dcf9-2c48-485b-bf01-ff6f44838b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b16e87dc-b69a-43ff-9c83-b7453e094bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QA-73</value>
      <webElementGuid>bdde6bd9-cde6-4059-8669-90d03b61715f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-polSelect-result-520t-73&quot;)</value>
      <webElementGuid>d6d099ba-bac4-423a-ac9f-860682f40120</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-polSelect-result-520t-73']</value>
      <webElementGuid>fbf4ee30-c28e-476f-8988-8154257ca4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-polSelect-results']/li[3]</value>
      <webElementGuid>4f7ef25e-6ad8-412e-a849-5b12dedb431f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA-74'])[2]/following::li[1]</value>
      <webElementGuid>263e3854-95f2-4994-94bb-c5b6a696f3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[4]/following::li[2]</value>
      <webElementGuid>dfa94747-9cc2-4773-a5c8-d260c44cf06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA-72'])[2]/preceding::li[1]</value>
      <webElementGuid>15606c55-c43e-41f4-9178-d3953f292808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[3]</value>
      <webElementGuid>e7acec40-61c3-44bd-b4a2-8982d9127b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-polSelect-result-520t-73' and (text() = 'QA-73' or . = 'QA-73')]</value>
      <webElementGuid>a04b0dae-00b9-45ee-85a0-95441ef05b1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
