<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_operationyj.com</name>
   <tag></tag>
   <elementGuidId>cb395c65-58ee-4b59-a58d-6ed9fb458d61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dropdownMenuLink']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdownMenuLink > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ca4d29a5-1ed6-455c-a68c-17f147275243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/users/edit</value>
      <webElementGuid>fa3272ab-f2ba-4a48-bf2f-171551a42785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>operation@yj.com</value>
      <webElementGuid>c31245bd-80c9-429e-bfd8-89add2cc99f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownMenuLink&quot;)/a[1]</value>
      <webElementGuid>288b2d77-e784-400a-acdc-f0d9e02bfabe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdownMenuLink']/a</value>
      <webElementGuid>bbb10230-7e7a-4ffd-8da1-4190c2467659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'operation@yj.com')]</value>
      <webElementGuid>fd455b2d-51a9-49c0-9f67-f6a4ea9ee9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Menu'])[1]/following::a[2]</value>
      <webElementGuid>5c9f4494-7741-4bc0-ad28-8b3a0d786bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PO-L List'])[1]/preceding::a[1]</value>
      <webElementGuid>e59b64c3-060f-4ad6-b166-94e9ca22b906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='operation@yj.com']/parent::*</value>
      <webElementGuid>cded3950-9a74-44ee-ace2-d548d55601eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/users/edit')]</value>
      <webElementGuid>5efbc764-4633-459d-aa98-763a41e66492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>daed967e-34f6-4b41-83d9-d322e0c77db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/users/edit' and (text() = 'operation@yj.com' or . = 'operation@yj.com')]</value>
      <webElementGuid>ac5bd895-adf5-40dc-bd9c-424b100af534</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
