<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Q.C</name>
   <tag></tag>
   <elementGuidId>a9a03dbf-1dbd-414e-99f0-0363a3311988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mx-5.d-flex.align-items-center.justify-content-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div/div[2]/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>836469c6-84cf-4bf1-8087-a65c006bbeb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-5 d-flex align-items-center justify-content-center</value>
      <webElementGuid>b289a7d8-d576-423a-9a57-b1d229d14b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pols/qc</value>
      <webElementGuid>27d22bf3-717f-45cf-b615-c160ce219f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Q.C.</value>
      <webElementGuid>c4661c72-20ff-475a-b005-1825ff36d688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;info&quot;]/div[@class=&quot;boder-blue&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;menu-tab d-flex mb-5 mt-5&quot;]/a[@class=&quot;mx-5 d-flex align-items-center justify-content-center&quot;]</value>
      <webElementGuid>3f89bd8d-3f40-4fba-9de1-c5526ec631c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[2]/div/a[2]</value>
      <webElementGuid>bbb75cac-d95d-400a-8321-48ab4ea93e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Q.C.')]</value>
      <webElementGuid>93881f30-6d7c-41eb-a714-43f6e75e7b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receive Item'])[1]/following::a[1]</value>
      <webElementGuid>3bd5aeaf-6df7-44da-b32a-acbb1e5a9754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receive &amp; Q.C.'])[1]/following::a[2]</value>
      <webElementGuid>b36c37de-a4e6-4c95-ab63-0256fd2b1b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packing'])[1]/preceding::a[1]</value>
      <webElementGuid>07218c36-68d6-455f-8124-0074890a3bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report'])[1]/preceding::a[2]</value>
      <webElementGuid>0878ccca-2387-4df3-8744-720664191644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Q.C.']/parent::*</value>
      <webElementGuid>67e41a9c-2f0e-40e7-84f5-b4ba9a90dd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pols/qc')]</value>
      <webElementGuid>618a376a-bb21-40e3-9ef7-0038fad2d520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>4b407bf5-33b4-4973-a2b0-61cd3d893aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pols/qc' and (text() = 'Q.C.' or . = 'Q.C.')]</value>
      <webElementGuid>81b06c7e-9877-42f5-874b-064c3b0b2bc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
