<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Fail_un-qc</name>
   <tag></tag>
   <elementGuidId>643617d9-ffa8-48c3-a084-31a93d840e65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#un-qc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='un-qc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>39a7b5e0-5679-4827-9dec-89f712a0d806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b1e705c8-faf7-4c91-b032-3134e8cea252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>un-qc</value>
      <webElementGuid>21447f45-6c08-4f64-8146-f5d259e013cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-close</value>
      <webElementGuid>f4a47fe9-4b08-41bc-a3b4-25e18a5481fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>un-qc</value>
      <webElementGuid>3913a147-7778-4486-a619-d29e6fa7accc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>click->qc#unQc</value>
      <webElementGuid>694b68b8-c5f6-4181-94da-5d23dacadd61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>72-2117</value>
      <webElementGuid>8f2eecc1-af67-48f2-993a-d7a1f45dc274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;un-qc&quot;)</value>
      <webElementGuid>27f6a2ed-d684-4181-9ba6-5db7c86fe7ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='un-qc']</value>
      <webElementGuid>ef1f96db-3d1e-4d7d-9f37-16664d8085cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='qcTable']/tbody/tr/td[11]/button</value>
      <webElementGuid>f43b6c8b-2366-42e3-8924-7e54a39cc335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/button</value>
      <webElementGuid>593db527-91ad-4d4c-b18b-f54a811818c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'un-qc' and @name = 'un-qc']</value>
      <webElementGuid>125ae31e-99bf-4e6e-aebc-7fb36fe798d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
