<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Scan barcode_input-qc</name>
   <tag></tag>
   <elementGuidId>4f24072d-848d-4498-8414-920789836a30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-qc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-qc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26236c5b-c17d-42ff-a4b8-3b9d187c65eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control barcode mb-3 me-3</value>
      <webElementGuid>8654ea34-cba5-48b1-ace0-85c2f2056356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-qc</value>
      <webElementGuid>b6e1cdeb-53f0-4553-8a29-09ea6718675a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Barcode</value>
      <webElementGuid>c7c6799c-4417-4469-8482-b2dd960e2ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>keyup->qc#scanBarcode</value>
      <webElementGuid>b762c504-2a9c-45fc-a54a-475a411bb8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b66c5e71-8c41-47bf-b2df-0bb79d638b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input-qc</value>
      <webElementGuid>10f3638e-9592-4e02-a452-01fd73a95235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-qc&quot;)</value>
      <webElementGuid>dd97d014-86cb-48d2-93f1-baedac6e51cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-qc']</value>
      <webElementGuid>6d02b759-5c8f-4c09-a7fb-7f83ed610d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[3]/div/div/input</value>
      <webElementGuid>cbb1067f-1b49-4bca-a0b4-fa8d9b69a765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>29c3c9ba-5ae5-4089-bc7f-284ac3f75952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-qc' and @placeholder = 'Barcode' and @type = 'text' and @name = 'input-qc']</value>
      <webElementGuid>e08e7354-4296-492f-9976-d3adbaf59290</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
