<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Scan barcode_input-receive</name>
   <tag></tag>
   <elementGuidId>e2d4c766-7dc1-4271-9eb5-a32d40c5ff5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-receive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-receive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edab7abc-2b00-4b09-b721-12be5175f1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control barcode mb-3 me-3</value>
      <webElementGuid>a4cd8beb-2602-4272-b705-2cf4e178816c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-receive</value>
      <webElementGuid>38c61591-76b9-4f4e-bf4b-2968ac9901d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Barcode</value>
      <webElementGuid>8febf7ce-2a3a-4b84-9d2e-5de06cd2205d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>keyup->receive-item#scanBarcode</value>
      <webElementGuid>3c42d87a-97d6-4486-aae4-fee9dcf60ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>122b1efe-b44f-41dc-aa5d-0b7552bfdb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input-receive</value>
      <webElementGuid>44eccb05-e791-4edf-bb0a-88777a4ae37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-receive&quot;)</value>
      <webElementGuid>5b4f5d7b-ba89-453b-adb3-f9ee4f347c52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-receive']</value>
      <webElementGuid>3ef0abd7-371e-4da8-a98a-416ba75b3289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[3]/div/input</value>
      <webElementGuid>df737026-4bef-451c-a702-11921a700dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>6975873b-f6a7-440d-96d4-c06c6ad3ee6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-receive' and @placeholder = 'Barcode' and @type = 'text' and @name = 'input-receive']</value>
      <webElementGuid>69c6f538-5fe4-4904-b52b-b0ab3987c8de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
