<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_designyj.com</name>
   <tag></tag>
   <elementGuidId>32225fd7-ec3d-4eab-a718-92497b169c20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dropdownMenuLink']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdownMenuLink > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ffbcbe35-070a-4230-a9f6-64d1f683d2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/users/edit</value>
      <webElementGuid>01515bfc-8442-4dfe-8ade-67c3701d24f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>design@yj.com</value>
      <webElementGuid>b7a0d227-bc87-4b45-b85e-479a95644cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownMenuLink&quot;)/a[1]</value>
      <webElementGuid>e3b8e737-a583-48d0-8587-9dd4843958a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdownMenuLink']/a</value>
      <webElementGuid>151815ce-d0be-4fcc-a56f-f0111d7b8eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'design@yj.com')]</value>
      <webElementGuid>d5582b48-cf93-4582-b289-cb64cafde3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Menu'])[1]/following::a[2]</value>
      <webElementGuid>0c301b13-38e1-45c2-8bbc-0558d4e95bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer List'])[1]/preceding::a[1]</value>
      <webElementGuid>8df0cc9f-59a7-41d8-9fe3-d8dc5ad2e0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='design@yj.com']/parent::*</value>
      <webElementGuid>9a9e9097-f410-41ef-aa81-fe67e289220f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/users/edit')]</value>
      <webElementGuid>b309d7a2-c03e-4ffe-8a56-2a3086c06a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>373860f7-6f98-4e6d-88da-803300f439ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/users/edit' and (text() = 'design@yj.com' or . = 'design@yj.com')]</value>
      <webElementGuid>696ba2eb-dc07-4ca3-a44f-a0b8495fe6e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
