<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qty_productproduct_materials_attribut_75f79e</name>
   <tag></tag>
   <elementGuidId>2525dfca-2298-4400-82c1-f88f0b41cc34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_product_materials_attributes_1666252641415_quantity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_product_materials_attributes_1666252641415_quantity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78d83f11-0143-4ce2-92c3-b1887e5c7145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-end</value>
      <webElementGuid>b8275ae8-97b1-4391-8ec6-385314d3b199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>67f3288d-2e3f-41f4-be01-666a440cc99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>06443df8-4a12-488a-b7ae-67bd047ad93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-material-target</name>
      <type>Main</type>
      <value>qty</value>
      <webElementGuid>3b772490-142e-48e5-aa50-7311786acfff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5225322c-f79b-4fcb-8585-103620661a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[product_materials_attributes][1666252641415][quantity]</value>
      <webElementGuid>5d4b5661-548a-4539-a404-2b8bba05b6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_product_materials_attributes_1666252641415_quantity</value>
      <webElementGuid>d633785e-68db-445d-8bca-33bbc39b5df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_product_materials_attributes_1666252641415_quantity&quot;)</value>
      <webElementGuid>f019fe68-24b3-45f0-bf1e-cafe5e5fee26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_product_materials_attributes_1666252641415_quantity']</value>
      <webElementGuid>0999d311-6aea-415d-8cb9-d9e859bf6a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product_materials']/div/div[4]/input</value>
      <webElementGuid>4072a028-0d44-4352-8503-7e174801ef9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/input</value>
      <webElementGuid>19a12fef-b0dd-49f8-95a9-9722cc68ea86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'product[product_materials_attributes][1666252641415][quantity]' and @id = 'product_product_materials_attributes_1666252641415_quantity']</value>
      <webElementGuid>046d4887-ce1c-4995-b064-6fc68cb15f07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
