<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Size_productin_house</name>
   <tag></tag>
   <elementGuidId>f56fd50b-65ba-42da-9c81-268fd95c393f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='itsInhouseBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#itsInhouseBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41732710-e839-4c67-88b5-4f2e762e2df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-box-size3 mx-2</value>
      <webElementGuid>fe69f2bb-6a85-4f86-912f-e3c79e2598ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itsInhouseBtn</value>
      <webElementGuid>1d3fc648-89e0-4103-84d8-e8093d948c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>click->check-btn#toggleDisplayAddBtn click->check-btn#checkInhouseMaterials</value>
      <webElementGuid>580b1f7f-6243-4d98-8434-a95c312a1e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>07b87b11-45cf-4a3a-94dc-e1b6216a8877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9c65987b-cc94-4bcb-9d7f-d356ffd063cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[in_house]</value>
      <webElementGuid>7f5d67d1-8485-4919-8aff-227aea9d1b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itsInhouseBtn&quot;)</value>
      <webElementGuid>575b9be2-e2f2-41dd-b00c-0c0fdd6bae3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='itsInhouseBtn']</value>
      <webElementGuid>52bea375-4c1e-42ff-a2c5-d3acc9c50805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div/div[2]/div/div[2]/div/div[4]/div/input[2]</value>
      <webElementGuid>3406340f-fb62-4e28-bfe6-a48799ec57b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>53673dbf-a66a-406c-9af8-44ec02a3d4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'itsInhouseBtn' and @type = 'checkbox' and @name = 'product[in_house]']</value>
      <webElementGuid>0076da89-40c6-4522-871d-da70e150bdb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
