<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UPC_productupc</name>
   <tag></tag>
   <elementGuidId>28b81e11-8b76-4a15-99fc-4ba0537e1bca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_upc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_upc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8195706a-3e60-4746-b24a-b194518641f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>171b8046-90ca-4d29-a727-d6766d57c379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4852b15d-9d34-48ef-9a09-256dfa5c943b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[upc]</value>
      <webElementGuid>1ed1a13a-53b3-4199-b277-4ff2296f470d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_upc</value>
      <webElementGuid>09c069b5-092a-4ee0-b2f5-27d34c3e91a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_upc&quot;)</value>
      <webElementGuid>6597945e-9ea2-4f8d-b844-d3781f679245</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_upc']</value>
      <webElementGuid>3f7f5341-a563-474f-996e-8bacd612acb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div/div[2]/div/div[4]/div/div[2]/input</value>
      <webElementGuid>e7f1f30b-9d79-4702-8ad2-f3a61ef83a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>230ccc70-82e4-45a1-ba9a-df0aa2f97f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'product[upc]' and @id = 'product_upc']</value>
      <webElementGuid>9a7a3845-010a-4650-b461-da8e7f92cc3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
