<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PO-L Cost_productpol_cost</name>
   <tag></tag>
   <elementGuidId>898bf40e-3979-48ca-b3e5-ff55b910cd2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_pol_cost']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_pol_cost</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>952442f1-be69-4cc6-bc5e-c5adfef68434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0a1969d7-1034-45c3-abb4-99ef67ea93d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>48507588-057e-4062-b1f8-de18de231057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>73d01fc3-8d3c-4f43-906a-bb2836fae88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>87dbadf0-f57d-43c4-8b1e-bbdc9af79dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9a7c4c7d-017d-47f1-8bde-4006907a7a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[pol_cost]</value>
      <webElementGuid>df5c4741-0d58-4c88-93c9-6df2b561d751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_pol_cost</value>
      <webElementGuid>10583487-8343-4ca4-a25a-f9e821660dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_pol_cost&quot;)</value>
      <webElementGuid>b8a1a729-723b-4b93-93c9-fdd5f557b5ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_pol_cost']</value>
      <webElementGuid>41d6e373-7992-4b30-b944-1315471e51c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div/div[2]/div/div[4]/div[2]/div[4]/input</value>
      <webElementGuid>6b1fd677-4cca-4e16-9c4b-9bd3b54dc730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/input</value>
      <webElementGuid>06c0c3d3-4c79-4d57-96c9-51dcca7a765f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'product[pol_cost]' and @id = 'product_pol_cost']</value>
      <webElementGuid>feda980b-03db-47fb-b2eb-e5a31ce63ce6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
