<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HTS Code_producthts_code</name>
   <tag></tag>
   <elementGuidId>a0aa222f-d168-47fd-b87c-53ab948379e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_hts_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_hts_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98c2a676-82e2-43eb-81ff-0b59205970ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3ffa4ba7-1123-4b22-9f66-69be5135b7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb64c333-0b72-4e8c-8830-d2ab57763650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[hts_code]</value>
      <webElementGuid>ec569c30-b81b-4578-9fdf-9f0b763ba6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_hts_code</value>
      <webElementGuid>3cdeb3b1-355d-4ae3-8c18-0453dd5ea966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_hts_code&quot;)</value>
      <webElementGuid>d1ec40f3-32ce-418c-8e58-6a4e5486fd15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_hts_code']</value>
      <webElementGuid>09eef191-2581-4125-abb9-ecfa15fccc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div/div[2]/div/div[4]/div[2]/div[2]/input</value>
      <webElementGuid>f0c0b4b3-0223-443c-adf3-187724705991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>513c6f16-6adb-47d6-a569-86054ee3df7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'product[hts_code]' and @id = 'product_hts_code']</value>
      <webElementGuid>e61effac-8653-45bd-8961-31c73c2830e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
