<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_A-Button200</name>
   <tag></tag>
   <elementGuidId>6f7ab961-a9e6-44ee-b358-84c2c7980578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-product_product_materials_attributes_1666256486798_material_id-result-zifl-239']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-product_product_materials_attributes_1666256486798_material_id-result-zifl-239</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8e08c555-812f-430b-8da9-c44a7b4d2c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--selectable select2-results__option--highlighted</value>
      <webElementGuid>439398d0-c1c8-4f50-b89d-01257ddecf62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-product_product_materials_attributes_1666256486798_material_id-result-zifl-239</value>
      <webElementGuid>f708b074-d2b9-4d59-a9ab-5e17b61d1d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e16fd367-c977-4854-b2c0-9f948e88002f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-data-select2-product_product_materials_attributes_1666256486798_material_id-result-zifl-239</value>
      <webElementGuid>a95b438e-4775-4b18-93d9-7ff6efc31c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5cf697b2-a133-4e34-8b63-af427cf2eb4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A-Button200</value>
      <webElementGuid>a32cefb3-40f2-43da-b4aa-030022e0e2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-product_product_materials_attributes_1666256486798_material_id-result-zifl-239&quot;)</value>
      <webElementGuid>f5a2c176-6ade-4f44-bf72-c21bc4550ba4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-product_product_materials_attributes_1666256486798_material_id-result-zifl-239']</value>
      <webElementGuid>c05c590b-3bef-44bd-a95f-a5f5452ce083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-product_product_materials_attributes_1666256486798_material_id-results']/li[2]</value>
      <webElementGuid>1e5c8996-5276-45bf-84ab-8c04d795833b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a Material'])[3]/following::li[1]</value>
      <webElementGuid>c9a2aae3-e14b-4d8e-8110-8b964031f2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::li[2]</value>
      <webElementGuid>55209572-56bd-4622-9d02-ad5f55fe4c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-E-trim250.55'])[2]/preceding::li[1]</value>
      <webElementGuid>1ea7d9fa-6da2-4949-afaf-f9aa88c2e587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-Fabric150'])[2]/preceding::li[2]</value>
      <webElementGuid>c7830ea2-8d22-4ba4-b1ae-77037fe4f80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[2]</value>
      <webElementGuid>2a58f29c-38fa-4c7c-aa17-12267c0cfb02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-product_product_materials_attributes_1666256486798_material_id-result-zifl-239' and (text() = 'A-Button200' or . = 'A-Button200')]</value>
      <webElementGuid>a3de4fc3-69c5-410c-be65-7312e6c9ef4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
