<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_A-Button200</name>
   <tag></tag>
   <elementGuidId>27a98350-932b-40cc-9ad4-4c8469809ee0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-product_product_materials_attributes_1666252598977_material_id-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-product_product_materials_attributes_1666252598977_material_id-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9748bfa3-e7da-4b83-9191-df3821723120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>fa1395a7-ada7-4b49-935f-49a5cb8edfb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-product_product_materials_attributes_1666252598977_material_id-container</value>
      <webElementGuid>ff5c3dfe-5c4c-455b-8df8-718838b4b1ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a8a3f09a-615a-43f5-8727-13ccaced7f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0bf6f0b1-cd76-4b2c-9e55-6734a69ebf9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>A-Button200</value>
      <webElementGuid>2d8692a9-0ee5-4998-8b2f-f618e1e72237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A-Button200</value>
      <webElementGuid>3b290da5-5bd3-4706-b5cc-40b6972a12df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-product_product_materials_attributes_1666252598977_material_id-container&quot;)</value>
      <webElementGuid>61f66c27-e772-46c8-8787-1f103be70559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-product_product_materials_attributes_1666252598977_material_id-container']</value>
      <webElementGuid>d65aab9b-cf42-4b7b-ae25-86f51cc02f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product_materials']/div/div/span/span/span/span</value>
      <webElementGuid>b04adce8-212a-4434-9a30-51615b47bb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material'])[2]/following::span[4]</value>
      <webElementGuid>34932c83-8351-4c75-a91a-851ef9aa7ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material'])[1]/following::span[4]</value>
      <webElementGuid>8109adad-2724-4e50-9a59-d36f71de5a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please choose a Material.'])[1]/preceding::span[3]</value>
      <webElementGuid>bea4733a-5c7f-4233-ac71-0f74e334a869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material type'])[1]/preceding::span[3]</value>
      <webElementGuid>7cffc8c2-dc42-407f-a6b0-a68869ea5363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>842467d2-6329-485c-a60b-c0fc74143388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-product_product_materials_attributes_1666252598977_material_id-container' and @title = 'A-Button200' and (text() = 'A-Button200' or . = 'A-Button200')]</value>
      <webElementGuid>ac55da03-7ce8-4d9b-a632-48734d932982</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
