<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select a Material</name>
   <tag></tag>
   <elementGuidId>4655a63c-5a4e-40b6-8299-aada2ceb3b9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-product_product_materials_attributes_1666252641415_material_id-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-product_product_materials_attributes_1666252641415_material_id-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d51b44bd-0e95-416f-a6cc-c798378a84f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>7a860227-2790-43cf-a94f-02b19d46472a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-product_product_materials_attributes_1666252641415_material_id-container</value>
      <webElementGuid>46da9651-a5b6-4ba6-82bf-414ae09ef482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>9a13fe61-0720-40c1-a15d-de35679b80a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e1ef4255-3407-4d48-a6e9-79f2a74051d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select a Material </value>
      <webElementGuid>a3a3866d-55b5-44d0-9744-d0e04cdfe22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a Material </value>
      <webElementGuid>920f1d50-e5c1-4e9c-8b08-5dc1625b3406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-product_product_materials_attributes_1666252641415_material_id-container&quot;)</value>
      <webElementGuid>2f1017af-dceb-4f0a-be6b-849d116a8786</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-product_product_materials_attributes_1666252641415_material_id-container']</value>
      <webElementGuid>a686ab40-bc0b-40c5-b52a-14d9b50e8cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product_materials']/div/div/span/span/span/span</value>
      <webElementGuid>a2c3e8c1-3345-4c1c-98d1-59eec02a78ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material'])[2]/following::span[4]</value>
      <webElementGuid>df53e801-d167-47fa-a265-084a9f01f21a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material'])[1]/following::span[4]</value>
      <webElementGuid>9df46aca-a469-4749-bc35-ca447ccb14ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please choose a Material.'])[1]/preceding::span[3]</value>
      <webElementGuid>942342d5-6f60-474e-8fa7-3a8cce34213c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material type'])[1]/preceding::span[3]</value>
      <webElementGuid>b36b7b59-8f8b-4fe5-a54f-c93fead1b4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>ac2f2aca-246f-43f3-b31c-86c03d926e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-product_product_materials_attributes_1666252641415_material_id-container' and @title = 'Select a Material ' and (text() = 'Select a Material ' or . = 'Select a Material ')]</value>
      <webElementGuid>39841b46-5ba8-4372-a575-a0801dd41e22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
