<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Descrtiption Thai_productdescrip_th</name>
   <tag></tag>
   <elementGuidId>f3a8fe03-4ee8-46de-b4a1-dc827e5234c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='product_descrip_th']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_descrip_th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3b496bf8-5cad-4de4-9c08-179cdf82be0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>adda06be-ed4a-4d3a-a53a-9125c7f57d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[descrip_th]</value>
      <webElementGuid>71d142ba-8074-4b7d-9cac-4231ad39cdff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_descrip_th</value>
      <webElementGuid>21783414-fe64-498b-9d70-e94ecb6271cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_descrip_th&quot;)</value>
      <webElementGuid>ac6600c9-8e01-48a5-b5bf-10981ef7a4c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='product_descrip_th']</value>
      <webElementGuid>d69e09e3-c6a6-4c14-9ab0-2cf62b7da9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div/div[2]/div/div[2]/div[3]/textarea</value>
      <webElementGuid>7e5ca026-8ae7-4864-990a-2282183a39f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/textarea</value>
      <webElementGuid>d78ab054-20ee-4d79-a7a2-5fa943724023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'product[descrip_th]' and @id = 'product_descrip_th']</value>
      <webElementGuid>dbf1652c-8e14-4def-849a-68617bd356f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
