<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Descrtiption English_productdescrip_en</name>
   <tag></tag>
   <elementGuidId>d51ac3e9-d65c-40d7-b4ab-1f19caf85da2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='product_descrip_en']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_descrip_en</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>58c6f440-9e9d-4036-88aa-c6c6d4f46e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2c605049-f098-43ee-815a-a64f7956be03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[descrip_en]</value>
      <webElementGuid>5e4e1939-085d-4b98-aa2c-f45f0c2b34c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_descrip_en</value>
      <webElementGuid>5050a4ad-efda-4d1a-a652-85da41505724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_descrip_en&quot;)</value>
      <webElementGuid>ec61f52e-8a3d-4065-8a51-8549dfdbd15b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='product_descrip_en']</value>
      <webElementGuid>c7b6bf3a-88aa-4fcc-810c-6264527768df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div/div[2]/div/div[2]/div[2]/textarea</value>
      <webElementGuid>ef462f49-6136-48d4-b519-bf0304e84b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>d6f0ba44-5201-452a-830e-24dec23cfc18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'product[descrip_en]' and @id = 'product_descrip_en']</value>
      <webElementGuid>87c4c551-1c39-408a-a33f-74789c61021a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
