<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Color Description Thai_productcolo_9f46a2</name>
   <tag></tag>
   <elementGuidId>956e7fa1-22d8-4683-bd89-e217fde0eea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='product_color_descrip']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_color_descrip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>341c1a60-ef55-42f8-a0de-15d47e15fbb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8e3a7d15-6af2-4624-9720-da6d543989ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[color_descrip]</value>
      <webElementGuid>29f6a2e5-800c-42b4-aada-fd9716e3e9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_color_descrip</value>
      <webElementGuid>420e43b2-704f-4e7d-b0bb-7e6ac4ce4be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_color_descrip&quot;)</value>
      <webElementGuid>8d703659-0244-48d5-936d-39430e5b3179</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='product_color_descrip']</value>
      <webElementGuid>4326dc4c-c0ff-4b73-b4e4-6974bc56e4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div/div[2]/div/div[2]/div[4]/textarea</value>
      <webElementGuid>84735c16-30ee-4c7a-b7b9-7b5d3e352d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/textarea</value>
      <webElementGuid>d88f069c-88b6-4e1c-b1d0-93cdbd87d422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'product[color_descrip]' and @id = 'product_color_descrip']</value>
      <webElementGuid>647db036-2b4c-49f4-99e4-93da475a5b72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
